name: smart_sme_app
description: "Smart SME Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 State Management (STABLE)
  get: ^4.7.3

  # 🔐 Biometric (STABLE & COMPATIBLE)
  local_auth: ^2.1.6

  # 💾 Local Storage (RECOMMENDED)
  get_storage: ^2.1.1

  # 🌐 (OPTIONAL - nanti untuk API)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true